import React, { useState } from 'react';
import { Bell, Check, Trash2, Filter } from 'lucide-react';
import Sidebar from '../components/Sidebar';
import NotificationCard from '../components/NotificationCard';
import './Notifications.css';

export default function Notifications() {
  const [notifications, setNotifications] = useState([
    {
      id: 'n1',
      title: 'Air Quality Hazard Warning',
      location: 'Delhi NCR',
      type: 'danger',
      message: 'Severe thermal boundary inversion detected. AQI has crossed 280 threshold. Sensitive groups should remain indoors.',
      time: '12 minutes ago',
      read: false
    },
    {
      id: 'n2',
      title: 'Evening Particulate Spike Rule',
      location: 'Coimbatore',
      type: 'warning',
      message: 'Apriori pattern miner matched evening low wind condition (<6 km/h). PM2.5 particulate level elevated to 156.',
      time: '45 minutes ago',
      read: false
    },
    {
      id: 'n3',
      title: 'Optimal Alpine Air Baseline',
      location: 'Shimla Ridge',
      type: 'success',
      message: 'Atmospheric sensor stream confirms pristine baseline (AQI 28). Ideal conditions for outdoor recreation.',
      time: '3 hours ago',
      read: true
    }
  ]);

  const [filter, setFilter] = useState('ALL');

  const handleDismiss = (id) => {
    setNotifications(prev => prev.filter(n => n.id !== id));
  };

  const handleMarkRead = (id) => {
    setNotifications(prev => prev.map(n => n.id === id ? { ...n, read: true } : n));
  };

  const handleMarkAllRead = () => {
    setNotifications(prev => prev.map(n => ({ ...n, read: true })));
  };

  const filtered = notifications.filter(n => {
    if (filter === 'UNREAD') return !n.read;
    return true;
  });

  return (
    <div className="dashboard-layout-root">
      <Sidebar />

      <main className="dashboard-main-viewport">
        {/* Page Header */}
        <header className="page-header-block notif-header-flex">
          <div>
            <span className="page-kicker">REAL-TIME ATMOSPHERIC DISPATCH</span>
            <h1 className="page-headline">Environmental Alerts & Notifications</h1>
            <p className="page-subtext">
              Automated notifications generated by thermal inversion patterns and AQI threshold triggers.
            </p>
          </div>

          <div className="notif-top-btns">
            <button className="btn-secondary" onClick={handleMarkAllRead}>
              <Check size={16} />
              <span>Mark All Read</span>
            </button>
          </div>
        </header>

        {/* Filter Pills */}
        <div className="notif-filter-bar">
          <button
            className={`notif-filter-btn ${filter === 'ALL' ? 'active' : ''}`}
            onClick={() => setFilter('ALL')}
          >
            All Notifications ({notifications.length})
          </button>
          <button
            className={`notif-filter-btn ${filter === 'UNREAD' ? 'active' : ''}`}
            onClick={() => setFilter('UNREAD')}
          >
            Unread ({notifications.filter(n => !n.read).length})
          </button>
        </div>

        {/* Notification Stack */}
        <div className="notifications-stack-list">
          {filtered.length === 0 ? (
            <div className="empty-notif-box glass-card">
              <Bell size={42} className="empty-bell" />
              <h3>Zero Active Notifications</h3>
              <p>All atmospheric telemetry warnings have been acknowledged.</p>
            </div>
          ) : (
            filtered.map(n => (
              <NotificationCard
                key={n.id}
                notification={n}
                onDismiss={handleDismiss}
                onMarkRead={handleMarkRead}
              />
            ))
          )}
        </div>
      </main>
    </div>
  );
}
